### ISSUE TITLE
recently opened files / notebooks section

### ISSUE THREAD

**Issue by benbovy** [jupyterlab-contrib/jlab-enhanced-launcher#11]
Thank you very much for this extension! It's a something that I wished for a long time!

One feature suggestion: it would be nice to have a section for re-opening the files and/or notebooks that we used the most recently. This would save a lot of clicks/navigation in the file browser.

**Comment by benbovy** [comment]
Or maybe a `File > Open Recent...` menu item in Jupyterlab would be enough (https://github.com/jupyterlab/jupyterlab/issues/5924)...

**Comment by fcollonval** [comment]
Thanks for the suggestion @benbovy 

Would you mind providing a sketch of the UI you have in mind for that feature? In particular long path name won't display nicely in cards - so any suggestion is welcomed.

You may be interested in that extension: https://github.com/NERSC/jupyterlab-recents

> It is not compatible with JupyterLab 3 at this time.

**Comment by benbovy** [comment]
Hmm I don't have a clear idea in mind on how would look the UI. I opened this issue before seeing that there was an open issue in Jupyterlab, so I probably won't really need a section in this launcher if there's a menu item available. I'll wait for `jupyterlab-recents` be compatible with Jupyterlab 3.

Thanks for the pointer @fcollonval! Feel free to close this issue.

**Comment by fcollonval** [comment]
jupyterlab-recents is available on JupyterLab 3. If someone is interested in this feature, it should be implemented on that extension - using the ability to add items to the launcher (see Xref issue).
